// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tea_Cmd from "rescript-tea/src/Tea_Cmd.res.mjs";
import * as Database from "./Database.res.mjs";
import * as Tea_Http from "rescript-tea/src/Tea_Http.res.mjs";
import * as Tea_Json from "rescript-tea/src/Tea_Json.res.mjs";

let proxyBase = "http://localhost:4000";

function executeQuery(profile, query, dtEnabled) {
  let url = proxyBase + `/api/` + profile.id + profile.executePath;
  let body = Object.fromEntries([
    [
      "query",
      query
    ],
    [
      "dt",
      dtEnabled
    ]
  ]);
  return Tea_Http.postJson(url, body, Tea_Json.value, result => ({
    TAG: "QueryResult",
    _0: result
  }));
}

function checkHealth(profile) {
  let url = proxyBase + `/api/` + profile.id + profile.healthPath;
  return Tea_Http.getString(url, result => ({
    TAG: "HealthResult",
    _0: profile.id,
    _1: result
  }));
}

function checkAllHealth() {
  return Tea_Cmd.batch(Database.all().map(checkHealth));
}

export {
  proxyBase,
  executeQuery,
  checkHealth,
  checkAllHealth,
}
/* No side effect */
