// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Api from "./Api.res.mjs";
import * as Subs from "./Subs.res.mjs";
import * as View from "./View.res.mjs";
import * as Model from "./Model.res.mjs";
import * as Route from "./Route.res.mjs";
import * as Update from "./Update.res.mjs";
import * as Tea_App from "rescript-tea/src/Tea_App.res.mjs";
import * as Tea_Cmd from "rescript-tea/src/Tea_Cmd.res.mjs";
import * as Tea_Url from "@anthropics/cadre-router/src/tea/Tea_Url.res.mjs";
import * as Database from "./Database.res.mjs";

let BrowserLocation = {};

function setupPopstateListener(onUrlChange) {
  window.addEventListener("popstate", () => {
    let rawUrl = window.location.pathname + window.location.search + window.location.hash;
    onUrlChange(Tea_Url.parse(rawUrl));
  });
}

function init(_flags) {
  let currentUrl = Tea_Url.current();
  let route = Route.fromUrl(currentUrl);
  let model = Model.init(route);
  let routerCmd = Tea_Cmd.effect(dispatch => setupPopstateListener(url => dispatch({
    TAG: "UrlChanged",
    _0: url
  })));
  let customProfilesCmd = Database.loadCustomProfiles();
  let healthCmd = Api.checkAllHealth();
  return [
    model,
    Tea_Cmd.batch([
      routerCmd,
      customProfilesCmd,
      healthCmd
    ])
  ];
}

let AppComponent = Tea_App.MakeWithDispatch({
  init: init,
  update: Update.update,
  view: View.make,
  subscriptions: Subs.subscriptions
});

function App(props) {
  return AppComponent.make({
    flags: undefined
  });
}

let make = App;

export {
  BrowserLocation,
  setupPopstateListener,
  AppComponent,
  make,
}
/* AppComponent Not a pure module */
