// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.res.mjs";
import * as Client from "/vendor/esm/react-dom-client.mjs";
import * as JsxRuntime from "/vendor/esm/react-jsx-runtime.mjs";

let rootElement = document.getElementById("root");

if (rootElement == null) {
  console.error("NQC Web UI: Could not find #root element. Check index.html.");
} else {
  let root = Client.createRoot(rootElement);
  root.render(JsxRuntime.jsx(App.make, {}));
}

/* rootElement Not a pure module */
