// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Msg from "./Msg.res.mjs";
import * as Database from "./Database.res.mjs";

function init(route) {
  let activeDb;
  activeDb = typeof route !== "object" ? undefined : Database.findById(route.dbId);
  let dtEnabled;
  dtEnabled = typeof route !== "object" ? false : route.dt;
  let format;
  format = typeof route !== "object" ? "Table" : Msg.formatFromString(route.format);
  return {
    route: route,
    databases: Database.all(),
    activeDb: activeDb,
    connection: "Disconnected",
    healthMap: {},
    query: "",
    results: undefined,
    format: format,
    dtEnabled: dtEnabled,
    history: [],
    error: undefined
  };
}

export {
  init,
}
/* No side effect */
