// Generated by ReScript, PLEASE EDIT WITH CARE


function formatToString(fmt) {
  switch (fmt) {
    case "Table" :
      return "table";
    case "Json" :
      return "json";
    case "Csv" :
      return "csv";
  }
}

function formatFromString(s) {
  let match = s.toLowerCase();
  switch (match) {
    case "csv" :
      return "Csv";
    case "json" :
      return "Json";
    default:
      return "Table";
  }
}

export {
  formatToString,
  formatFromString,
}
/* No side effect */
