// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as Tea_QueryParams from "@anthropics/cadre-router/src/tea/Tea_QueryParams.res.mjs";

function fromUrl(url) {
  let qs = url.query;
  let params = qs !== undefined ? Tea_QueryParams.parse(qs) : ({});
  let dt = Core__Option.getOr(Tea_QueryParams.getBool(params, "dt"), false);
  let format = Tea_QueryParams.getOr(params, "format", "table");
  let segments = url.path.split("/").filter(s => s.length > 0);
  let len = segments.length;
  if (len >= 3) {
    return "NotFound";
  }
  switch (len) {
    case 0 :
      return "Picker";
    case 1 :
      return "NotFound";
    case 2 :
      let match = segments[0];
      if (match !== "query") {
        return "NotFound";
      }
      let dbId = segments[1];
      return {
        TAG: "Query",
        dbId: dbId,
        dt: dt,
        format: format
      };
  }
}

function toPath(route) {
  if (typeof route !== "object") {
    if (route === "Picker") {
      return "/";
    } else {
      return "/404";
    }
  }
  let format = route.format;
  let base = "/query/" + route.dbId;
  let params = {};
  if (route.dt) {
    params["dt"] = "true";
  }
  if (format !== "table") {
    params["format"] = format;
  }
  let qs = Tea_QueryParams.build(params);
  return base + qs;
}

export {
  fromUrl,
  toPath,
}
/* No side effect */
