// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tea_Sub from "rescript-tea/src/Tea_Sub.res.mjs";

function subscriptions(_model) {
  return Tea_Sub.none;
}

export {
  subscriptions,
}
/* No side effect */
