// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tea_Sub from "/node_modules/rescript-tea/src/Tea_Sub.res.mjs";

function subscriptions(_model) {
  return Tea_Sub.none;
}

export {
  subscriptions,
}
/* No side effect */
