// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Api from "./Api.res.mjs";
import * as Msg from "./Msg.res.mjs";
import * as Route from "./Route.res.mjs";
import * as Tea_Cmd from "rescript-tea/src/Tea_Cmd.res.mjs";
import * as Tea_Url from "@anthropics/cadre-router/src/tea/Tea_Url.res.mjs";
import * as Database from "./Database.res.mjs";
import * as Tea_Http from "rescript-tea/src/Tea_Http.res.mjs";
import * as Tea_Navigation from "@anthropics/cadre-router/src/tea/Tea_Navigation.res.mjs";

function navigateTo(model, path) {
  let url = Tea_Url.parse(path);
  let route = Route.fromUrl(url);
  let activeDb;
  activeDb = typeof route !== "object" ? undefined : Database.findById(route.dbId);
  let dtEnabled;
  dtEnabled = typeof route !== "object" ? model.dtEnabled : route.dt;
  let format;
  format = typeof route !== "object" ? model.format : Msg.formatFromString(route.format);
  let match = model.activeDb;
  let newModel_databases = model.databases;
  let newModel_connection = activeDb !== undefined ? "Connecting" : "Disconnected";
  let newModel_healthMap = model.healthMap;
  let newModel_query = model.query;
  let newModel_results = match !== undefined && (activeDb === undefined || match.id === activeDb.id) ? model.results : undefined;
  let newModel_history = model.history;
  let newModel_error = model.error;
  let newModel = {
    route: route,
    databases: newModel_databases,
    activeDb: activeDb,
    connection: newModel_connection,
    healthMap: newModel_healthMap,
    query: newModel_query,
    results: newModel_results,
    format: format,
    dtEnabled: dtEnabled,
    history: newModel_history,
    error: newModel_error
  };
  let navCmd = Tea_Cmd.effect(_dispatch => Tea_Navigation.execute({
    TAG: "Push",
    _0: url
  }));
  let healthCmd = activeDb !== undefined ? Api.checkHealth(activeDb) : Tea_Cmd.none;
  return [
    newModel,
    Tea_Cmd.batch([
      navCmd,
      healthCmd
    ])
  ];
}

function update(msg, model) {
  if (typeof msg !== "object") {
    switch (msg) {
      case "SubmitQuery" :
        let db = model.activeDb;
        if (db === undefined) {
          return [
            model,
            Tea_Cmd.none
          ];
        }
        if (model.query.trim().length <= 0) {
          return [
            model,
            Tea_Cmd.none
          ];
        }
        let entry_query = model.query;
        let entry_dbId = db.id;
        let entry_timestamp = Date.now();
        let entry = {
          query: entry_query,
          dbId: entry_dbId,
          timestamp: entry_timestamp
        };
        let newHistory = [entry].concat(model.history).slice(0, 50);
        let newModel_route = model.route;
        let newModel_databases = model.databases;
        let newModel_activeDb = model.activeDb;
        let newModel_connection = model.connection;
        let newModel_healthMap = model.healthMap;
        let newModel_query = model.query;
        let newModel_results = model.results;
        let newModel_format = model.format;
        let newModel_dtEnabled = model.dtEnabled;
        let newModel = {
          route: newModel_route,
          databases: newModel_databases,
          activeDb: newModel_activeDb,
          connection: newModel_connection,
          healthMap: newModel_healthMap,
          query: newModel_query,
          results: newModel_results,
          format: newModel_format,
          dtEnabled: newModel_dtEnabled,
          history: newHistory,
          error: undefined
        };
        return [
          newModel,
          Api.executeQuery(db, model.query, model.dtEnabled)
        ];
      case "ToggleDt" :
        let newDt = !model.dtEnabled;
        let newModel_route$1 = model.route;
        let newModel_databases$1 = model.databases;
        let newModel_activeDb$1 = model.activeDb;
        let newModel_connection$1 = model.connection;
        let newModel_healthMap$1 = model.healthMap;
        let newModel_query$1 = model.query;
        let newModel_results$1 = model.results;
        let newModel_format$1 = model.format;
        let newModel_history = model.history;
        let newModel_error = model.error;
        let newModel$1 = {
          route: newModel_route$1,
          databases: newModel_databases$1,
          activeDb: newModel_activeDb$1,
          connection: newModel_connection$1,
          healthMap: newModel_healthMap$1,
          query: newModel_query$1,
          results: newModel_results$1,
          format: newModel_format$1,
          dtEnabled: newDt,
          history: newModel_history,
          error: newModel_error
        };
        let db$1 = model.activeDb;
        let path = Route.toPath({
          TAG: "Query",
          dbId: db$1 !== undefined ? db$1.id : "unknown",
          dt: newDt,
          format: Msg.formatToString(model.format)
        });
        let cmd = Tea_Cmd.effect(_dispatch => Tea_Navigation.execute({
          TAG: "Replace",
          _0: Tea_Url.parse(path)
        }));
        return [
          newModel$1,
          cmd
        ];
      case "ClearResults" :
        return [
          {
            route: model.route,
            databases: model.databases,
            activeDb: model.activeDb,
            connection: model.connection,
            healthMap: model.healthMap,
            query: model.query,
            results: undefined,
            format: model.format,
            dtEnabled: model.dtEnabled,
            history: model.history,
            error: model.error
          },
          Tea_Cmd.none
        ];
      case "DismissError" :
        return [
          {
            route: model.route,
            databases: model.databases,
            activeDb: model.activeDb,
            connection: model.connection,
            healthMap: model.healthMap,
            query: model.query,
            results: model.results,
            format: model.format,
            dtEnabled: model.dtEnabled,
            history: model.history,
            error: undefined
          },
          Tea_Cmd.none
        ];
    }
  } else {
    switch (msg.TAG) {
      case "UrlChanged" :
        let route = Route.fromUrl(msg._0);
        let activeDb;
        activeDb = typeof route !== "object" ? undefined : Database.findById(route.dbId);
        let dtEnabled;
        dtEnabled = typeof route !== "object" ? model.dtEnabled : route.dt;
        let format;
        format = typeof route !== "object" ? model.format : Msg.formatFromString(route.format);
        let healthCmd = activeDb !== undefined ? Api.checkHealth(activeDb) : Tea_Cmd.none;
        return [
          {
            route: route,
            databases: model.databases,
            activeDb: activeDb,
            connection: model.connection,
            healthMap: model.healthMap,
            query: model.query,
            results: model.results,
            format: format,
            dtEnabled: dtEnabled,
            history: model.history,
            error: model.error
          },
          healthCmd
        ];
      case "NavigateTo" :
        return navigateTo(model, msg._0);
      case "SelectDatabase" :
        let path$1 = "/query/" + msg._0;
        return navigateTo(model, path$1);
      case "UpdateQuery" :
        return [
          {
            route: model.route,
            databases: model.databases,
            activeDb: model.activeDb,
            connection: model.connection,
            healthMap: model.healthMap,
            query: msg._0,
            results: model.results,
            format: model.format,
            dtEnabled: model.dtEnabled,
            history: model.history,
            error: model.error
          },
          Tea_Cmd.none
        ];
      case "QueryResult" :
        let json = msg._0;
        if (json.TAG === "Ok") {
          return [
            {
              route: model.route,
              databases: model.databases,
              activeDb: model.activeDb,
              connection: model.connection,
              healthMap: model.healthMap,
              query: model.query,
              results: json._0,
              format: model.format,
              dtEnabled: model.dtEnabled,
              history: model.history,
              error: undefined
            },
            Tea_Cmd.none
          ];
        }
        let errMsg = Tea_Http.errorToString(json._0);
        return [
          {
            route: model.route,
            databases: model.databases,
            activeDb: model.activeDb,
            connection: model.connection,
            healthMap: model.healthMap,
            query: model.query,
            results: model.results,
            format: model.format,
            dtEnabled: model.dtEnabled,
            history: model.history,
            error: errMsg
          },
          Tea_Cmd.none
        ];
      case "HealthResult" :
        let err = msg._1;
        let dbId = msg._0;
        if (err.TAG === "Ok") {
          let healthMap = Object.fromEntries(Object.entries(model.healthMap).concat([[
              dbId,
              "Connected"
            ]]));
          let db$2 = model.activeDb;
          let connection = db$2 !== undefined && db$2.id === dbId ? "Connected" : model.connection;
          return [
            {
              route: model.route,
              databases: model.databases,
              activeDb: model.activeDb,
              connection: connection,
              healthMap: healthMap,
              query: model.query,
              results: model.results,
              format: model.format,
              dtEnabled: model.dtEnabled,
              history: model.history,
              error: model.error
            },
            Tea_Cmd.none
          ];
        }
        let errMsg$1 = Tea_Http.errorToString(err._0);
        let healthMap$1 = Object.fromEntries(Object.entries(model.healthMap).concat([[
            dbId,
            {
              TAG: "ConnectionError",
              _0: errMsg$1
            }
          ]]));
        let db$3 = model.activeDb;
        let connection$1 = db$3 !== undefined && db$3.id === dbId ? ({
            TAG: "ConnectionError",
            _0: errMsg$1
          }) : model.connection;
        return [
          {
            route: model.route,
            databases: model.databases,
            activeDb: model.activeDb,
            connection: connection$1,
            healthMap: healthMap$1,
            query: model.query,
            results: model.results,
            format: model.format,
            dtEnabled: model.dtEnabled,
            history: model.history,
            error: model.error
          },
          Tea_Cmd.none
        ];
      case "SetFormat" :
        let fmt = msg._0;
        let newModel_route$2 = model.route;
        let newModel_databases$2 = model.databases;
        let newModel_activeDb$2 = model.activeDb;
        let newModel_connection$2 = model.connection;
        let newModel_healthMap$2 = model.healthMap;
        let newModel_query$2 = model.query;
        let newModel_results$2 = model.results;
        let newModel_dtEnabled$1 = model.dtEnabled;
        let newModel_history$1 = model.history;
        let newModel_error$1 = model.error;
        let newModel$2 = {
          route: newModel_route$2,
          databases: newModel_databases$2,
          activeDb: newModel_activeDb$2,
          connection: newModel_connection$2,
          healthMap: newModel_healthMap$2,
          query: newModel_query$2,
          results: newModel_results$2,
          format: fmt,
          dtEnabled: newModel_dtEnabled$1,
          history: newModel_history$1,
          error: newModel_error$1
        };
        let db$4 = model.activeDb;
        let path$2 = Route.toPath({
          TAG: "Query",
          dbId: db$4 !== undefined ? db$4.id : "unknown",
          dt: model.dtEnabled,
          format: Msg.formatToString(fmt)
        });
        let cmd$1 = Tea_Cmd.effect(_dispatch => Tea_Navigation.execute({
          TAG: "Replace",
          _0: Tea_Url.parse(path$2)
        }));
        return [
          newModel$2,
          cmd$1
        ];
      case "HistorySelect" :
        let entry$1 = model.history[msg._0];
        if (entry$1 !== undefined) {
          return [
            {
              route: model.route,
              databases: model.databases,
              activeDb: model.activeDb,
              connection: model.connection,
              healthMap: model.healthMap,
              query: entry$1.query,
              results: model.results,
              format: model.format,
              dtEnabled: model.dtEnabled,
              history: model.history,
              error: model.error
            },
            Tea_Cmd.none
          ];
        } else {
          return [
            model,
            Tea_Cmd.none
          ];
        }
    }
  }
}

export {
  navigateTo,
  update,
}
/* No side effect */
