// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Query from "./Pages/Query.res.mjs";
import * as Header from "./Components/Header.res.mjs";
import * as Picker from "./Pages/Picker.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function make(model, dispatch) {
  let match = model.route;
  let tmp;
  tmp = typeof match !== "object" ? (
      match === "Picker" ? Picker.make(model, dispatch) : JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("div", {
              children: "404",
              className: "nqc-notfound__code"
            }),
            JsxRuntime.jsx("div", {
              children: "Page not found"
            }),
            JsxRuntime.jsx("a", {
              children: "Back to database picker",
              className: "nqc-notfound__link",
              href: "/",
              onClick: e => {
                e.preventDefault();
                dispatch({
                  TAG: "NavigateTo",
                  _0: "/"
                });
              }
            })
          ],
          className: "nqc-notfound"
        })
    ) : Query.make(model, dispatch);
  return JsxRuntime.jsxs("div", {
    children: [
      Header.make(model, dispatch),
      tmp
    ]
  });
}

export {
  make,
}
/* Query Not a pure module */
