// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Status from "../Components/Status.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function renderCard(profile, healthState, dispatch) {
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("span", {
            children: profile.displayName,
            className: "nqc-card__name"
          }),
          JsxRuntime.jsx("span", {
            children: profile.languageName,
            className: "nqc-card__lang"
          })
        ],
        className: "nqc-card__header"
      }),
      JsxRuntime.jsx("div", {
        children: profile.description,
        className: "nqc-card__desc"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("span", {
            children: ":" + profile.defaultPort.toString(),
            className: "nqc-card__port"
          }),
          Status.make(healthState, false)
        ],
        className: "nqc-card__footer"
      })
    ],
    className: "nqc-card",
    onClick: param => dispatch({
      TAG: "SelectDatabase",
      _0: profile.id
    })
  }, profile.id);
}

function make(model, dispatch) {
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h1", {
        children: "NextGen Query Client",
        className: "nqc-picker__title"
      }),
      JsxRuntime.jsx("p", {
        children: "Select a database engine to start querying.",
        className: "nqc-picker__subtitle"
      }),
      JsxRuntime.jsx("div", {
        children: model.databases.map(db => {
          let healthState = Core__Option.getOr(model.healthMap[db.id], "Disconnected");
          return renderCard(db, healthState, dispatch);
        }),
        className: "nqc-picker__grid"
      })
    ],
    className: "nqc-picker"
  });
}

export {
  renderCard,
  make,
}
/* Status Not a pure module */
