// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Editor from "../Components/Editor.res.mjs";
import * as Results from "../Components/Results.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function make(model, dispatch) {
  let db = model.activeDb;
  if (db === undefined) {
    return JsxRuntime.jsx("div", {
      children: JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: "Database not found.",
            style: {
              fontSize: "18px",
              marginBottom: "16px"
            }
          }),
          JsxRuntime.jsx("a", {
            children: "Back to database picker",
            className: "nqc-notfound__link",
            href: "/",
            onClick: e => {
              e.preventDefault();
              dispatch({
                TAG: "NavigateTo",
                _0: "/"
              });
            }
          })
        ],
        style: {
          alignItems: "center",
          color: "#8b949e",
          display: "flex",
          flexDirection: "column",
          height: "100%",
          justifyContent: "center"
        }
      }),
      className: "nqc-query"
    });
  }
  let errMsg = model.error;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          errMsg !== undefined ? JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("span", {
                  children: errMsg
                }),
                JsxRuntime.jsx("button", {
                  children: "\u00D7",
                  className: "nqc-error__dismiss",
                  onClick: param => dispatch("DismissError")
                })
              ],
              className: "nqc-error"
            }) : null,
          Editor.make(model.query, db.prompt, db.keywords, model.history, dispatch)
        ],
        className: "nqc-query__editor-pane"
      }),
      JsxRuntime.jsx("div", {
        children: Results.make(model.results, model.format),
        className: "nqc-query__results-pane"
      })
    ],
    className: "nqc-query"
  });
}

export {
  make,
}
/* Editor Not a pure module */
