// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function make(query, prompt, keywords, history, dispatch) {
  let isEmpty = query.trim().length === 0;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("textarea", {
        className: "nqc-editor__textarea",
        placeholder: prompt + "Enter your query here...",
        value: query,
        onKeyDown: e => {
          let key = e.key;
          let ctrl = e.ctrlKey || e.metaKey;
          if (key === "Enter" && ctrl) {
            e.preventDefault();
            return dispatch("SubmitQuery");
          }
        },
        onChange: e => {
          let value = e.target.value;
          dispatch({
            TAG: "UpdateQuery",
            _0: value
          });
        }
      }),
      keywords.length > 0 ? JsxRuntime.jsx("div", {
          children: keywords.map(kw => JsxRuntime.jsx("span", {
            children: kw,
            className: "nqc-keywords__chip",
            onClick: param => {
              let sep = query.length > 0 && !query.endsWith(" ") ? " " : "";
              dispatch({
                TAG: "UpdateQuery",
                _0: query + sep + kw + " "
              });
            }
          }, kw)),
          className: "nqc-keywords"
        }) : null,
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("span", {
                children: "Ctrl+Enter to execute",
                className: "nqc-editor__hint"
              }),
              history.length > 0 ? JsxRuntime.jsx("div", {
                  children: JsxRuntime.jsxs("details", {
                    children: [
                      JsxRuntime.jsx("summary", {
                        children: `History (` + history.length.toString() + `)`,
                        style: {
                          color: "#8b949e",
                          cursor: "pointer",
                          fontFamily: "var(--font-mono)",
                          fontSize: "12px"
                        }
                      }),
                      JsxRuntime.jsx("ul", {
                        children: history.map((entry, idx) => {
                          let display = entry.query.length > 60 ? entry.query.slice(0, 57) + "..." : entry.query;
                          return JsxRuntime.jsx("li", {
                            children: display,
                            className: "nqc-history__item",
                            onClick: param => dispatch({
                              TAG: "HistorySelect",
                              _0: idx
                            })
                          }, idx.toString());
                        }),
                        className: "nqc-history__list"
                      })
                    ]
                  }),
                  className: "nqc-history"
                }) : null
            ],
            style: {
              alignItems: "center",
              display: "flex",
              gap: "16px"
            }
          }),
          JsxRuntime.jsx("button", {
            children: "Execute",
            className: "nqc-editor__submit",
            disabled: isEmpty,
            onClick: param => dispatch("SubmitQuery")
          })
        ],
        className: "nqc-editor__bar"
      })
    ],
    className: "nqc-editor"
  });
}

export {
  make,
}
/* react/jsx-runtime Not a pure module */
