// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Status from "./Status.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function make(model, dispatch) {
  let db = model.activeDb;
  return JsxRuntime.jsxs("header", {
    children: [
      JsxRuntime.jsxs("a", {
        children: [
          "NQC",
          JsxRuntime.jsx("span", {
            children: "NextGen Query Client",
            style: {
              color: "#8b949e",
              fontSize: "13px",
              fontWeight: "400"
            }
          })
        ],
        className: "nqc-header__brand",
        href: "/",
        onClick: e => {
          e.preventDefault();
          dispatch({
            TAG: "NavigateTo",
            _0: "/"
          });
        }
      }),
      JsxRuntime.jsx("nav", {
        children: db !== undefined ? JsxRuntime.jsxs(JsxRuntime.Fragment, {
            children: [
              JsxRuntime.jsx("span", {
                children: db.languageName,
                className: "nqc-header__db-badge"
              }),
              Status.make(model.connection, true),
              db.supportsDt ? JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsx("span", {
                      className: "nqc-toggle__switch"
                    }),
                    JsxRuntime.jsx("span", {
                      children: "DT"
                    }),
                    model.dtEnabled ? JsxRuntime.jsx("span", {
                        children: "on",
                        className: "nqc-dt-badge"
                      }) : null
                  ],
                  className: "nqc-toggle" + (
                    model.dtEnabled ? " nqc-toggle--active" : ""
                  ),
                  onClick: param => dispatch("ToggleDt")
                }) : null,
              JsxRuntime.jsx("div", {
                children: [
                  "Table",
                  "Json",
                  "Csv"
                ].map(fmt => {
                  let label;
                  switch (fmt) {
                    case "Table" :
                      label = "Table";
                      break;
                    case "Json" :
                      label = "JSON";
                      break;
                    case "Csv" :
                      label = "CSV";
                      break;
                  }
                  let isActive = model.format === fmt;
                  return JsxRuntime.jsx("button", {
                    children: label,
                    className: "nqc-format-tab" + (
                      isActive ? " nqc-format-tab--active" : ""
                    ),
                    onClick: param => dispatch({
                      TAG: "SetFormat",
                      _0: fmt
                    })
                  }, label);
                }),
                className: "nqc-format-tabs"
              })
            ]
          }) : null,
        className: "nqc-header__nav"
      })
    ],
    className: "nqc-header"
  });
}

export {
  make,
}
/* Status Not a pure module */
