// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function make(state, showLabel) {
  let match;
  if (typeof state !== "object") {
    switch (state) {
      case "Disconnected" :
        match = [
          "nqc-status__dot",
          "Disconnected"
        ];
        break;
      case "Connecting" :
        match = [
          "nqc-status__dot nqc-status__dot--connecting",
          "Connecting..."
        ];
        break;
      case "Connected" :
        match = [
          "nqc-status__dot nqc-status__dot--connected",
          "Connected"
        ];
        break;
    }
  } else {
    match = [
      "nqc-status__dot nqc-status__dot--error",
      "Error: " + state._0
    ];
  }
  return JsxRuntime.jsxs("span", {
    children: [
      JsxRuntime.jsx("span", {
        className: match[0]
      }),
      showLabel ? JsxRuntime.jsx("span", {
          children: match[1]
        }) : null
    ],
    className: "nqc-status"
  });
}

export {
  make,
}
/* react/jsx-runtime Not a pure module */
