// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";
import * as Lith_Property_Types from "./Lith_Property_Types.res.js";
import * as Lith_Property_Generators from "./Lith_Property_Generators.res.js";

function runProperty(configOpt, name, generator, toString, property) {
  var config = configOpt !== undefined ? configOpt : Lith_Property_Types.defaultConfig;
  var seed = Core__Option.getOr(config.seed, Date.now() | 0);
  var rng = Lith_Property_Generators.makeRng(seed);
  if (config.verbose) {
    console.log("Running property: " + name);
    console.log("  Seed: " + seed.toString());
    console.log("  Iterations: " + config.iterations.toString());
  }
  var loop = function (iteration) {
    if (iteration > config.iterations) {
      return {
              TAG: "Passed",
              iterations: config.iterations
            };
    }
    var value = generator(rng);
    try {
      if (property(value)) {
        return loop(iteration + 1 | 0);
      }
      var counterexample = toString(value);
      return {
              TAG: "Failed",
              iteration: iteration,
              counterexample: counterexample,
              shrunk: undefined
            };
    }
    catch (raw_e){
      var e = Caml_js_exceptions.internalToOCamlException(raw_e);
      if (e.RE_EXN_ID !== Js_exn.$$Error) {
        return {
                TAG: "Errored",
                iteration: iteration,
                error: "Unknown exception"
              };
      }
      var msg = Core__Option.getOr(e._1.message, "Unknown error");
      return {
              TAG: "Errored",
              iteration: iteration,
              error: msg
            };
    }
  };
  return loop(1);
}

function printResult(name, result) {
  switch (result.TAG) {
    case "Passed" :
        console.log("✓ " + name + ": PASSED (" + result.iterations.toString() + " iterations)");
        return ;
    case "Failed" :
        var shrunk = result.shrunk;
        console.log("✗ " + name + ": FAILED at iteration " + result.iteration.toString());
        console.log("  Counterexample: " + result.counterexample);
        if (shrunk !== undefined) {
          console.log("  Shrunk to: " + shrunk);
          return ;
        } else {
          return ;
        }
    case "Errored" :
        console.log("✗ " + name + ": ERROR at iteration " + result.iteration.toString());
        console.log("  Error: " + result.error);
        return ;
    
  }
}

function isPassing(result) {
  switch (result.TAG) {
    case "Passed" :
        return true;
    case "Failed" :
    case "Errored" :
        return false;
    
  }
}

function runSuite(configOpt, tests) {
  var passed = {
    contents: 0
  };
  var failed = {
    contents: 0
  };
  var errored = {
    contents: 0
  };
  console.log("\n=== Property Test Suite ===\n");
  tests.forEach(function (param) {
        var result = param[1]();
        printResult(param[0], result);
        switch (result.TAG) {
          case "Passed" :
              passed.contents = passed.contents + 1 | 0;
              return ;
          case "Failed" :
              failed.contents = failed.contents + 1 | 0;
              return ;
          case "Errored" :
              errored.contents = errored.contents + 1 | 0;
              return ;
          
        }
      });
  console.log("\n=== Summary ===");
  console.log("Passed: " + passed.contents.toString());
  console.log("Failed: " + failed.contents.toString());
  console.log("Errored: " + errored.contents.toString());
  return {
          passed: passed.contents,
          failed: failed.contents,
          errored: errored.contents
        };
}

export {
  runProperty ,
  printResult ,
  isPassing ,
  runSuite ,
}
/* No side effect */
