// Generated by ReScript, PLEASE EDIT WITH CARE


var allStatementTypes = [
  "Select",
  "Insert",
  "Update",
  "Delete",
  "Create",
  "Drop",
  "Explain",
  "Introspect"
];

function statementTypeToString(st) {
  switch (st) {
    case "Select" :
        return "SELECT";
    case "Insert" :
        return "INSERT";
    case "Update" :
        return "UPDATE";
    case "Delete" :
        return "DELETE";
    case "Create" :
        return "CREATE";
    case "Drop" :
        return "DROP";
    case "Explain" :
        return "EXPLAIN";
    case "Introspect" :
        return "INTROSPECT";
    
  }
}

function compareOpToString(op) {
  switch (op) {
    case "Eq" :
        return "=";
    case "Ne" :
        return "!=";
    case "Lt" :
        return "<";
    case "Le" :
        return "<=";
    case "Gt" :
        return ">";
    case "Ge" :
        return ">=";
    case "Like" :
        return "LIKE";
    case "In" :
        return "IN";
    
  }
}

var allCompareOps = [
  "Eq",
  "Ne",
  "Lt",
  "Le",
  "Gt",
  "Ge",
  "Like",
  "In"
];

function valueToString(v) {
  if (typeof v !== "object") {
    return "null";
  }
  switch (v.TAG) {
    case "StringVal" :
        return "\"" + v._0 + "\"";
    case "IntVal" :
    case "FloatVal" :
        return v._0.toString();
    case "BoolVal" :
        if (v._0) {
          return "true";
        } else {
          return "false";
        }
    case "ArrayVal" :
        return "[" + v._0.map(valueToString).join(", ") + "]";
    
  }
}

var defaultConfig = {
  iterations: 100,
  seed: undefined,
  maxShrinks: 100,
  verbose: false
};

export {
  defaultConfig ,
  allStatementTypes ,
  statementTypeToString ,
  compareOpToString ,
  allCompareOps ,
  valueToString ,
}
/* No side effect */
