// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Types from "./Types.res.mjs";
import * as Decoders from "./Decoders.res.mjs";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let baseUrl = "";

async function fetchJson(url) {
  try {
    let resp = await fetch(url, {
      method: "GET"
    });
    if (resp.ok) {
      let data = await resp.json();
      return {
        TAG: "Ok",
        _0: data
      };
    }
    let body = await resp.text();
    return {
      TAG: "Error",
      _0: `HTTP ` + String(resp.status) + `: ` + body
    };
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    return {
      TAG: "Error",
      _0: String(exn)
    };
  }
}

async function fetchKnots(filtersOpt) {
  let filters = filtersOpt !== undefined ? filtersOpt : Types.emptyFilters;
  let params = [];
  let cn = filters.crossingNumber;
  if (cn !== undefined) {
    params.push("crossing_number=" + String(cn));
  }
  let g = filters.genus;
  if (g !== undefined) {
    params.push("genus=" + String(g));
  }
  if (filters.nameSearch !== "") {
    params.push("name=" + encodeURIComponent(filters.nameSearch));
  }
  let queryStr = params.length !== 0 ? "?" + params.join("&") : "";
  let result = await fetchJson(baseUrl + "/api/knots" + queryStr);
  if (result.TAG === "Ok") {
    return Decoders.decodeKnotList(result._0);
  } else {
    return {
      TAG: "Error",
      _0: result._0
    };
  }
}

async function fetchKnot(name) {
  let result = await fetchJson(baseUrl + "/api/knots/" + encodeURIComponent(name));
  if (result.TAG === "Ok") {
    return Decoders.decodeKnot(result._0);
  } else {
    return {
      TAG: "Error",
      _0: result._0
    };
  }
}

async function fetchStatistics() {
  let result = await fetchJson(baseUrl + "/api/statistics");
  if (result.TAG === "Ok") {
    return Decoders.decodeStatistics(result._0);
  } else {
    return {
      TAG: "Error",
      _0: result._0
    };
  }
}

async function postQuery(src, formatOpt, maxRowsOpt) {
  let format = formatOpt !== undefined ? formatOpt : "auto";
  let maxRows = maxRowsOpt !== undefined ? maxRowsOpt : 1000;
  try {
    let bodyObj = {};
    bodyObj["query"] = src;
    bodyObj["format"] = format;
    bodyObj["max_rows"] = maxRows;
    let bodyStr = JSON.stringify(bodyObj);
    let resp = await fetch(baseUrl + "/api/query", {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: bodyStr
    });
    let json = await resp.json();
    if (!resp.ok) {
      return {
        TAG: "Error",
        _0: Decoders.decodeQueryError(json)
      };
    }
    let r = Decoders.decodeQueryResponse(json);
    if (r.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: r._0
      };
    } else {
      return {
        TAG: "Error",
        _0: {
          errorKind: "decode_error",
          message: r._0,
          line: undefined,
          col: undefined
        }
      };
    }
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    return {
      TAG: "Error",
      _0: {
        errorKind: "network_error",
        message: String(exn),
        line: undefined,
        col: undefined
      }
    };
  }
}

export {
  baseUrl,
  fetchJson,
  fetchKnots,
  fetchKnot,
  fetchStatistics,
  postQuery,
}
/* No side effect */
