// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Api from "./Api.res.mjs";
import * as Route from "./Route.res.mjs";
import * as Types from "./Types.res.mjs";
import * as React from "react";
import * as Page_Query from "./Page_Query.res.mjs";
import * as View_Helpers from "./View_Helpers.res.mjs";
import * as Page_KnotList from "./Page_KnotList.res.mjs";
import * as Page_Dashboard from "./Page_Dashboard.res.mjs";
import * as Page_KnotDetail from "./Page_KnotDetail.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  let match = React.useReducer((model, msg) => {
    if (typeof msg !== "object") {
      return {
        route: Route.fromUrl(),
        stats: model.stats,
        knots: model.knots,
        knotDetail: model.knotDetail,
        filters: model.filters
      };
    }
    switch (msg.TAG) {
      case "NavigateTo" :
        let route = msg._0;
        history.pushState(null, "", Route.toPath(route));
        return {
          route: route,
          stats: model.stats,
          knots: model.knots,
          knotDetail: model.knotDetail,
          filters: model.filters
        };
      case "GotStatistics" :
        let stats = msg._0;
        if (stats.TAG === "Ok") {
          return {
            route: model.route,
            stats: {
              TAG: "Success",
              _0: stats._0
            },
            knots: model.knots,
            knotDetail: model.knotDetail,
            filters: model.filters
          };
        } else {
          return {
            route: model.route,
            stats: {
              TAG: "Failure",
              _0: stats._0
            },
            knots: model.knots,
            knotDetail: model.knotDetail,
            filters: model.filters
          };
        }
      case "GotKnots" :
        let knots = msg._0;
        if (knots.TAG === "Ok") {
          return {
            route: model.route,
            stats: model.stats,
            knots: {
              TAG: "Success",
              _0: knots._0
            },
            knotDetail: model.knotDetail,
            filters: model.filters
          };
        } else {
          return {
            route: model.route,
            stats: model.stats,
            knots: {
              TAG: "Failure",
              _0: knots._0
            },
            knotDetail: model.knotDetail,
            filters: model.filters
          };
        }
      case "GotKnotDetail" :
        let knot = msg._0;
        if (knot.TAG === "Ok") {
          return {
            route: model.route,
            stats: model.stats,
            knots: model.knots,
            knotDetail: {
              TAG: "Success",
              _0: knot._0
            },
            filters: model.filters
          };
        } else {
          return {
            route: model.route,
            stats: model.stats,
            knots: model.knots,
            knotDetail: {
              TAG: "Failure",
              _0: knot._0
            },
            filters: model.filters
          };
        }
      case "SetFilters" :
        return {
          route: model.route,
          stats: model.stats,
          knots: "Loading",
          knotDetail: model.knotDetail,
          filters: msg._0
        };
    }
  }, {
    route: Route.fromUrl(),
    stats: "NotAsked",
    knots: "NotAsked",
    knotDetail: "NotAsked",
    filters: Types.emptyFilters
  });
  let dispatch = match[1];
  let model = match[0];
  React.useEffect(() => {
    let handler = param => dispatch("UrlChanged");
    window.addEventListener("popstate", handler);
    return () => {
      window.removeEventListener("popstate", handler);
    };
  }, []);
  React.useEffect(() => {
    let name = model.route;
    if (typeof name !== "object") {
      switch (name) {
        case "Dashboard" :
          if (model.stats === "NotAsked") {
            Api.fetchStatistics().then(result => {
              dispatch({
                TAG: "GotStatistics",
                _0: result
              });
              return Promise.resolve();
            });
          }
          break;
        case "KnotList" :
          if (model.knots === "NotAsked") {
            Api.fetchKnots(undefined).then(result => {
              dispatch({
                TAG: "GotKnots",
                _0: result
              });
              return Promise.resolve();
            });
          }
          break;
        case "Query" :
        case "NotFound" :
          break;
      }
    } else {
      Api.fetchKnot(name._0).then(result => {
        dispatch({
          TAG: "GotKnotDetail",
          _0: result
        });
        return Promise.resolve();
      });
    }
  }, [model.route]);
  React.useEffect(() => {
    if (model.route === "KnotList") {
      Api.fetchKnots(model.filters).then(result => {
        dispatch({
          TAG: "GotKnots",
          _0: result
        });
        return Promise.resolve();
      });
    }
  }, [model.filters]);
  let navigate = route => dispatch({
    TAG: "NavigateTo",
    _0: route
  });
  let match$1 = model.route;
  let tmp;
  if (typeof match$1 !== "object") {
    switch (match$1) {
      case "Dashboard" :
        tmp = JsxRuntime.jsx(Page_Dashboard.make, {
          stats: model.stats,
          onNavigate: navigate
        });
        break;
      case "KnotList" :
        tmp = JsxRuntime.jsx(Page_KnotList.make, {
          knots: model.knots,
          filters: model.filters,
          onFilterChange: f => dispatch({
            TAG: "SetFilters",
            _0: f
          }),
          onNavigate: navigate
        });
        break;
      case "Query" :
        tmp = JsxRuntime.jsx(Page_Query.make, {});
        break;
      case "NotFound" :
        tmp = JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("h1", {
              children: "404 - Not Found"
            }),
            JsxRuntime.jsx("p", {
              children: "The page you are looking for does not exist."
            }),
            JsxRuntime.jsx("button", {
              children: "Go Home",
              className: "btn-primary",
              onClick: param => dispatch({
                TAG: "NavigateTo",
                _0: "Dashboard"
              })
            })
          ],
          className: "not-found"
        });
        break;
    }
  } else {
    tmp = JsxRuntime.jsx(Page_KnotDetail.make, {
      knot: model.knotDetail,
      onNavigate: navigate
    });
  }
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx(View_Helpers.NavBar.make, {
        currentRoute: model.route,
        onNavigate: navigate
      }),
      JsxRuntime.jsx("main", {
        children: tmp,
        className: "content"
      }),
      JsxRuntime.jsx("footer", {
        children: JsxRuntime.jsx("p", {
          children: "QuandleDB — Powered by Skein.jl"
        }),
        className: "app-footer"
      })
    ],
    className: "app"
  });
}

let make = App;

export {
  make,
}
/* react Not a pure module */
