// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Js_json from "@rescript/runtime/lib/es6/Js_json.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";

function decodeKnot(json) {
  let obj = Js_json.classify(json);
  if (typeof obj !== "object") {
    return {
      TAG: "Error",
      _0: "Expected JSON object for knot"
    };
  }
  if (obj.TAG !== "JSONObject") {
    return {
      TAG: "Error",
      _0: "Expected JSON object for knot"
    };
  }
  let obj$1 = obj._0;
  let str = key => {
    let v = Js_dict.get(obj$1, key);
    if (v === undefined) {
      return {
        TAG: "Error",
        _0: `Missing field: ` + key
      };
    }
    let s = Js_json.classify(v);
    if (typeof s !== "object") {
      if (s === "JSONNull") {
        return {
          TAG: "Error",
          _0: `Missing field: ` + key
        };
      } else {
        return {
          TAG: "Error",
          _0: `Expected string for ` + key
        };
      }
    } else if (s.TAG === "JSONString") {
      return {
        TAG: "Ok",
        _0: s._0
      };
    } else {
      return {
        TAG: "Error",
        _0: `Expected string for ` + key
      };
    }
  };
  let int_ = key => {
    let v = Js_dict.get(obj$1, key);
    if (v === undefined) {
      return {
        TAG: "Error",
        _0: `Missing field: ` + key
      };
    }
    let n = Js_json.classify(v);
    if (typeof n !== "object") {
      return {
        TAG: "Error",
        _0: `Expected int for ` + key
      };
    } else if (n.TAG === "JSONNumber") {
      return {
        TAG: "Ok",
        _0: n._0 | 0
      };
    } else {
      return {
        TAG: "Error",
        _0: `Expected int for ` + key
      };
    }
  };
  let optStr = key => {
    let v = Js_dict.get(obj$1, key);
    if (v === undefined) {
      return;
    }
    let s = Js_json.classify(v);
    if (typeof s !== "object" || s.TAG !== "JSONString") {
      return;
    } else {
      return s._0;
    }
  };
  let optInt = key => {
    let v = Js_dict.get(obj$1, key);
    if (v === undefined) {
      return;
    }
    let n = Js_json.classify(v);
    if (typeof n !== "object" || n.TAG !== "JSONNumber") {
      return;
    } else {
      return n._0 | 0;
    }
  };
  let v = Js_dict.get(obj$1, "gauss_code");
  let gaussCode;
  if (v !== undefined) {
    let arr = Js_json.classify(v);
    gaussCode = typeof arr !== "object" ? [] : (
        arr.TAG === "JSONArray" ? Belt_Array.keepMap(arr._0, item => {
            let n = Js_json.classify(item);
            if (typeof n !== "object" || n.TAG !== "JSONNumber") {
              return;
            } else {
              return n._0 | 0;
            }
          }) : []
      );
  } else {
    gaussCode = [];
  }
  let v$1 = Js_dict.get(obj$1, "metadata");
  let metadata;
  if (v$1 !== undefined) {
    let metaObj = Js_json.classify(v$1);
    if (typeof metaObj !== "object") {
      metadata = {};
    } else if (metaObj.TAG === "JSONObject") {
      let result = {};
      Belt_Array.forEach(Js_dict.entries(metaObj._0), param => {
        let s = Js_json.classify(param[1]);
        if (typeof s !== "object") {
          return;
        }
        if (s.TAG !== "JSONString") {
          return;
        }
        result[param[0]] = s._0;
      });
      metadata = result;
    } else {
      metadata = {};
    }
  } else {
    metadata = {};
  }
  let match = str("id");
  let match$1 = str("name");
  let match$2 = int_("crossing_number");
  let match$3 = int_("writhe");
  if (match.TAG === "Ok") {
    if (match$1.TAG === "Ok") {
      if (match$2.TAG === "Ok") {
        if (match$3.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              id: match._0,
              name: match$1._0,
              gaussCode: gaussCode,
              crossingNumber: match$2._0,
              writhe: match$3._0,
              genus: optInt("genus"),
              seifertCircleCount: optInt("seifert_circle_count"),
              determinant: optInt("determinant"),
              signature: optInt("signature"),
              alexanderPolynomial: optStr("alexander_polynomial"),
              alexanderDisplay: optStr("alexander_display"),
              jonesPolynomial: optStr("jones_polynomial"),
              jonesDisplay: optStr("jones_display"),
              homflyPolynomial: optStr("homfly_polynomial"),
              metadata: metadata,
              createdAt: Belt_Option.getWithDefault(optStr("created_at"), ""),
              updatedAt: Belt_Option.getWithDefault(optStr("updated_at"), "")
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: match$3._0
          };
        }
      } else {
        return {
          TAG: "Error",
          _0: match$2._0
        };
      }
    } else {
      return {
        TAG: "Error",
        _0: match$1._0
      };
    }
  } else {
    return {
      TAG: "Error",
      _0: match._0
    };
  }
}

function decodeKnotList(json) {
  let obj = Js_json.classify(json);
  if (typeof obj !== "object") {
    return {
      TAG: "Error",
      _0: "Expected JSON object for knot list"
    };
  }
  if (obj.TAG !== "JSONObject") {
    return {
      TAG: "Error",
      _0: "Expected JSON object for knot list"
    };
  }
  let obj$1 = obj._0;
  let v = Js_dict.get(obj$1, "knots");
  let knots;
  if (v !== undefined) {
    let arr = Js_json.classify(v);
    knots = typeof arr !== "object" ? [] : (
        arr.TAG === "JSONArray" ? Belt_Array.keepMap(arr._0, item => {
            let k = decodeKnot(item);
            if (k.TAG === "Ok") {
              return k._0;
            }
          }) : []
      );
  } else {
    knots = [];
  }
  let intField = (key, $$default) => {
    let v = Js_dict.get(obj$1, key);
    if (v === undefined) {
      return $$default;
    }
    let n = Js_json.classify(v);
    if (typeof n !== "object" || n.TAG !== "JSONNumber") {
      return $$default;
    } else {
      return n._0 | 0;
    }
  };
  return {
    TAG: "Ok",
    _0: {
      knots: knots,
      count: intField("count", knots.length),
      limit: intField("limit", 100),
      offset: intField("offset", 0)
    }
  };
}

function decodeIntDict(json) {
  let result = {};
  let obj = Js_json.classify(json);
  if (typeof obj === "object" && obj.TAG === "JSONObject") {
    Belt_Array.forEach(Js_dict.entries(obj._0), param => {
      let n = Js_json.classify(param[1]);
      if (typeof n !== "object") {
        return;
      }
      if (n.TAG !== "JSONNumber") {
        return;
      }
      result[param[0]] = n._0 | 0;
    });
  }
  return result;
}

function decodeStageTrace(json) {
  let obj = Js_json.classify(json);
  if (typeof obj !== "object") {
    return;
  }
  if (obj.TAG !== "JSONObject") {
    return;
  }
  let obj$1 = obj._0;
  let str = key => {
    let v = Js_dict.get(obj$1, key);
    if (v === undefined) {
      return "";
    }
    let s = Js_json.classify(v);
    if (typeof s !== "object" || s.TAG !== "JSONString") {
      return "";
    } else {
      return s._0;
    }
  };
  let int_ = key => {
    let v = Js_dict.get(obj$1, key);
    if (v === undefined) {
      return 0;
    }
    let n = Js_json.classify(v);
    if (typeof n !== "object" || n.TAG !== "JSONNumber") {
      return 0;
    } else {
      return n._0 | 0;
    }
  };
  let float_ = key => {
    let v = Js_dict.get(obj$1, key);
    if (v === undefined) {
      return 0.0;
    }
    let n = Js_json.classify(v);
    if (typeof n !== "object") {
      return 0.0;
    } else if (n.TAG === "JSONNumber") {
      return n._0;
    } else {
      return 0.0;
    }
  };
  return {
    stage: str("stage"),
    rowsIn: int_("rows_in"),
    rowsOut: int_("rows_out"),
    elapsedMs: float_("elapsed_ms"),
    note: str("note")
  };
}

function decodeQueryResponse(json) {
  let obj = Js_json.classify(json);
  if (typeof obj !== "object") {
    return {
      TAG: "Error",
      _0: "Expected JSON object for query response"
    };
  }
  if (obj.TAG !== "JSONObject") {
    return {
      TAG: "Error",
      _0: "Expected JSON object for query response"
    };
  }
  let obj$1 = obj._0;
  let float_ = (key, def) => {
    let v = Js_dict.get(obj$1, key);
    if (v === undefined) {
      return def;
    }
    let n = Js_json.classify(v);
    if (typeof n !== "object" || n.TAG !== "JSONNumber") {
      return def;
    } else {
      return n._0;
    }
  };
  let int_ = (key, def) => {
    let v = Js_dict.get(obj$1, key);
    if (v === undefined) {
      return def;
    }
    let n = Js_json.classify(v);
    if (typeof n !== "object" || n.TAG !== "JSONNumber") {
      return def;
    } else {
      return n._0 | 0;
    }
  };
  let bool_ = (key, def) => {
    let v = Js_dict.get(obj$1, key);
    if (v === undefined) {
      return def;
    }
    let match = Js_json.classify(v);
    if (typeof match === "object") {
      return def;
    }
    switch (match) {
      case "JSONFalse" :
        return false;
      case "JSONTrue" :
        return true;
      default:
        return def;
    }
  };
  let str_ = (key, def) => {
    let v = Js_dict.get(obj$1, key);
    if (v === undefined) {
      return def;
    }
    let s = Js_json.classify(v);
    if (typeof s !== "object" || s.TAG !== "JSONString") {
      return def;
    } else {
      return s._0;
    }
  };
  let v = Js_dict.get(obj$1, "rows");
  let rows;
  if (v !== undefined) {
    let arr = Js_json.classify(v);
    rows = typeof arr !== "object" ? [] : (
        arr.TAG === "JSONArray" ? arr._0 : []
      );
  } else {
    rows = [];
  }
  let v$1 = Js_dict.get(obj$1, "warnings");
  let warnings;
  if (v$1 !== undefined) {
    let arr$1 = Js_json.classify(v$1);
    warnings = typeof arr$1 !== "object" ? [] : (
        arr$1.TAG === "JSONArray" ? Belt_Array.keepMap(arr$1._0, item => {
            let s = Js_json.classify(item);
            if (typeof s !== "object" || s.TAG !== "JSONString") {
              return;
            } else {
              return s._0;
            }
          }) : []
      );
  } else {
    warnings = [];
  }
  let v$2 = Js_dict.get(obj$1, "trace");
  let trace;
  if (v$2 !== undefined) {
    let arr$2 = Js_json.classify(v$2);
    trace = typeof arr$2 !== "object" ? [] : (
        arr$2.TAG === "JSONArray" ? Belt_Array.keepMap(arr$2._0, decodeStageTrace) : []
      );
  } else {
    trace = [];
  }
  return {
    TAG: "Ok",
    _0: {
      rows: rows,
      count: int_("count", rows.length),
      parseTimeMs: float_("parse_time_ms", 0.0),
      evalTimeMs: float_("eval_time_ms", 0.0),
      totalMs: float_("total_ms", 0.0),
      pushdownUsed: bool_("pushdown_used", false),
      parseSource: str_("parse_source", "krl"),
      warnings: warnings,
      trace: trace
    }
  };
}

function decodeQueryError(json) {
  let obj = Js_json.classify(json);
  if (typeof obj !== "object") {
    return {
      errorKind: "decode_error",
      message: "Could not parse error response",
      line: undefined,
      col: undefined
    };
  }
  if (obj.TAG !== "JSONObject") {
    return {
      errorKind: "decode_error",
      message: "Could not parse error response",
      line: undefined,
      col: undefined
    };
  }
  let obj$1 = obj._0;
  let str_ = (key, def) => {
    let v = Js_dict.get(obj$1, key);
    if (v === undefined) {
      return def;
    }
    let s = Js_json.classify(v);
    if (typeof s !== "object" || s.TAG !== "JSONString") {
      return def;
    } else {
      return s._0;
    }
  };
  let optInt = key => {
    let v = Js_dict.get(obj$1, key);
    if (v === undefined) {
      return;
    }
    let n = Js_json.classify(v);
    if (typeof n !== "object" || n.TAG !== "JSONNumber") {
      return;
    } else {
      return n._0 | 0;
    }
  };
  return {
    errorKind: str_("error", "unknown"),
    message: str_("message", "Unknown error"),
    line: optInt("line"),
    col: optInt("col")
  };
}

function decodeStatistics(json) {
  let obj = Js_json.classify(json);
  if (typeof obj !== "object") {
    return {
      TAG: "Error",
      _0: "Expected JSON object for statistics"
    };
  }
  if (obj.TAG !== "JSONObject") {
    return {
      TAG: "Error",
      _0: "Expected JSON object for statistics"
    };
  }
  let obj$1 = obj._0;
  let intField = key => {
    let v = Js_dict.get(obj$1, key);
    if (v === undefined) {
      return;
    }
    let n = Js_json.classify(v);
    if (typeof n !== "object" || n.TAG !== "JSONNumber") {
      return;
    } else {
      return n._0 | 0;
    }
  };
  let v = Js_dict.get(obj$1, "crossing_distribution");
  let crossingDist = v !== undefined ? decodeIntDict(v) : ({});
  let v$1 = Js_dict.get(obj$1, "genus_distribution");
  let genusDist = v$1 !== undefined ? decodeIntDict(v$1) : ({});
  return {
    TAG: "Ok",
    _0: {
      totalKnots: Belt_Option.getWithDefault(intField("total_knots"), 0),
      minCrossings: intField("min_crossings"),
      maxCrossings: intField("max_crossings"),
      crossingDistribution: crossingDist,
      genusDistribution: genusDist,
      schemaVersion: Belt_Option.getWithDefault(intField("schema_version"), 0)
    }
  };
}

export {
  decodeKnot,
  decodeKnotList,
  decodeIntDict,
  decodeStageTrace,
  decodeQueryResponse,
  decodeQueryError,
  decodeStatistics,
}
/* No side effect */
