// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.res.mjs";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

let root = document.querySelector("#root");

if (root == null) {
  console.error("QuandleDB: could not find #root element");
} else {
  let rootElement = Client.createRoot(root);
  rootElement.render(JsxRuntime.jsx(App.make, {}));
}

/* root Not a pure module */
