// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as View_Helpers from "./View_Helpers.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Page_KnotDetail(props) {
  let onNavigate = props.onNavigate;
  let knot = props.knot;
  let renderField = (label, value) => JsxRuntime.jsxs("tr", {
    children: [
      JsxRuntime.jsx("th", {
        children: label
      }),
      JsxRuntime.jsx("td", {
        children: value
      })
    ]
  });
  let renderOptField = (label, value) => JsxRuntime.jsxs("tr", {
    children: [
      JsxRuntime.jsx("th", {
        children: label
      }),
      JsxRuntime.jsx("td", {
        children: value !== undefined ? value : "-"
      })
    ]
  });
  let tmp;
  if (typeof knot !== "object") {
    tmp = JsxRuntime.jsx(View_Helpers.Loading.make, {});
  } else if (knot.TAG === "Success") {
    let k = knot._0;
    tmp = JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsx("h1", {
          children: "Knot " + k.name
        }),
        JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h2", {
                  children: "Invariants"
                }),
                JsxRuntime.jsx("table", {
                  children: JsxRuntime.jsxs("tbody", {
                    children: [
                      renderField("Name", k.name),
                      renderField("Crossing Number", String(k.crossingNumber)),
                      renderField("Writhe", String(k.writhe)),
                      renderOptField("Genus", Belt_Option.map(k.genus, prim => String(prim))),
                      renderOptField("Seifert Circles", Belt_Option.map(k.seifertCircleCount, prim => String(prim))),
                      renderOptField("Determinant", Belt_Option.map(k.determinant, prim => String(prim))),
                      renderOptField("Signature", Belt_Option.map(k.signature, prim => String(prim))),
                      renderOptField("Alexander Polynomial", k.alexanderDisplay),
                      renderOptField("Jones Polynomial", k.jonesDisplay),
                      renderOptField("HOMFLY-PT", k.homflyPolynomial)
                    ]
                  }),
                  className: "detail-table"
                })
              ],
              className: "detail-section"
            }),
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h2", {
                  children: "Gauss Code"
                }),
                JsxRuntime.jsx("code", {
                  children: "[" + Belt_Array.map(k.gaussCode, prim => String(prim)).join(", ") + "]",
                  className: "gauss-code"
                })
              ],
              className: "detail-section"
            }),
            Object.keys(k.metadata).length !== 0 ? JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("h2", {
                    children: "Metadata"
                  }),
                  JsxRuntime.jsx("table", {
                    children: JsxRuntime.jsx("tbody", {
                      children: Belt_Array.map(Js_dict.entries(k.metadata), param => {
                        let key = param[0];
                        return JsxRuntime.jsxs("tr", {
                          children: [
                            JsxRuntime.jsx("th", {
                              children: key
                            }),
                            JsxRuntime.jsx("td", {
                              children: param[1]
                            })
                          ]
                        }, key);
                      })
                    }),
                    className: "detail-table"
                  })
                ],
                className: "detail-section"
              }) : null,
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("p", {
                  children: "Created: " + k.createdAt,
                  className: "meta-text"
                }),
                JsxRuntime.jsx("p", {
                  children: "Updated: " + k.updatedAt,
                  className: "meta-text"
                })
              ],
              className: "detail-section detail-meta"
            })
          ],
          className: "knot-detail-grid"
        })
      ]
    });
  } else {
    tmp = JsxRuntime.jsx(View_Helpers.ErrorDisplay.make, {
      message: knot._0
    });
  }
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("button", {
        children: "Back to List",
        className: "btn-back",
        onClick: param => onNavigate("KnotList")
      }),
      tmp
    ],
    className: "page-knot-detail"
  });
}

let make = Page_KnotDetail;

export {
  make,
}
/* View_Helpers Not a pure module */
