// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Api from "./Api.res.mjs";
import * as React from "react";
import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Js_json from "@rescript/runtime/lib/es6/Js_json.js";
import * as Belt_Int from "@rescript/runtime/lib/es6/Belt_Int.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as JsxRuntime from "react/jsx-runtime";

let examples = [
  [
    "Trefoil family",
    "from knots\n| filter crossing_number <= 5\n| sort crossing_number asc\n| return name, crossing_number, writhe, jones_polynomial"
  ],
  [
    "Equivalents of 3_1",
    "from knots\n| find_equivalent \"3_1\" via [jones_polynomial]\n| return name, crossing_number"
  ],
  [
    "SQL: figure-eight",
    "SELECT name, crossing_number, writhe\nFROM knots\nWHERE crossing_number = 4\nORDER BY name ASC"
  ],
  [
    "By determinant",
    "from knots\n| filter determinant == 3\n| return name, crossing_number, determinant, signature, alexander_polynomial"
  ],
  [
    "All invariants",
    "from invariants"
  ]
];

let initialState_input = Belt_Array.getExn(examples, 0)[1];

let initialState = {
  input: initialState_input,
  format: "auto",
  maxRows: "500",
  phase: "Idle",
  showTrace: false
};

function reducer(state, action) {
  if (typeof action !== "object") {
    if (action === "Submit") {
      return {
        input: state.input,
        format: state.format,
        maxRows: state.maxRows,
        phase: "Fetching",
        showTrace: state.showTrace
      };
    } else {
      return {
        input: state.input,
        format: state.format,
        maxRows: state.maxRows,
        phase: state.phase,
        showTrace: !state.showTrace
      };
    }
  }
  switch (action.TAG) {
    case "SetInput" :
      return {
        input: action._0,
        format: state.format,
        maxRows: state.maxRows,
        phase: state.phase,
        showTrace: state.showTrace
      };
    case "SetFormat" :
      return {
        input: state.input,
        format: action._0,
        maxRows: state.maxRows,
        phase: state.phase,
        showTrace: state.showTrace
      };
    case "SetMaxRows" :
      return {
        input: state.input,
        format: state.format,
        maxRows: action._0,
        phase: state.phase,
        showTrace: state.showTrace
      };
    case "GotOk" :
      return {
        input: state.input,
        format: state.format,
        maxRows: state.maxRows,
        phase: {
          TAG: "Done",
          _0: action._0
        },
        showTrace: state.showTrace
      };
    case "GotErr" :
      return {
        input: state.input,
        format: state.format,
        maxRows: state.maxRows,
        phase: {
          TAG: "Failed",
          _0: action._0
        },
        showTrace: state.showTrace
      };
    case "LoadExample" :
      return {
        input: action._0,
        format: state.format,
        maxRows: state.maxRows,
        phase: "Idle",
        showTrace: state.showTrace
      };
  }
}

function fmtMs(n) {
  let rounded = Math.round(n * 10.0) / 10.0;
  return rounded.toString() + "ms";
}

function cellText(json) {
  let s = Js_json.classify(json);
  if (typeof s !== "object") {
    switch (s) {
      case "JSONFalse" :
        return "false";
      case "JSONTrue" :
        return "true";
      case "JSONNull" :
        return "∅";
    }
  } else {
    switch (s.TAG) {
      case "JSONString" :
        return s._0;
      case "JSONNumber" :
        let n = s._0;
        if (Math.floor(n) === n) {
          return String(n | 0);
        } else {
          return n.toFixed(4);
        }
      case "JSONObject" :
        return "{…}";
      case "JSONArray" :
        return "[" + String(s._0.length) + " items]";
    }
  }
}

function getColumns(rows) {
  let first = Belt_Array.get(rows, 0);
  if (first === undefined) {
    return [];
  }
  let obj = Js_json.classify(first);
  if (typeof obj !== "object") {
    return [];
  } else if (obj.TAG === "JSONObject") {
    return Belt_Array.keep(Object.keys(obj._0), k => !k.startsWith("_"));
  } else {
    return [];
  }
}

function getCellValue(row, col) {
  let obj = Js_json.classify(row);
  if (typeof obj !== "object") {
    return "";
  }
  if (obj.TAG !== "JSONObject") {
    return "";
  }
  let v = Js_dict.get(obj._0, col);
  if (v !== undefined) {
    return cellText(v);
  } else {
    return "";
  }
}

function Page_Query$StatsBar(props) {
  let resp = props.resp;
  let pdBadge = resp.pushdownUsed ? JsxRuntime.jsx("span", {
      children: "pushdown",
      className: "badge badge-green"
    }) : null;
  let srcBadge = JsxRuntime.jsx("span", {
    children: resp.parseSource,
    className: "badge badge-blue"
  });
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("span", {
        children: String(resp.count) + " row" + (
          resp.count === 1 ? "" : "s"
        ),
        className: "stats-count"
      }),
      JsxRuntime.jsx("span", {
        children: "·",
        className: "stats-sep"
      }),
      JsxRuntime.jsx("span", {
        children: "parse " + fmtMs(resp.parseTimeMs) + " · eval " + fmtMs(resp.evalTimeMs) + " · total " + fmtMs(resp.totalMs),
        className: "stats-timing"
      }),
      JsxRuntime.jsx("span", {
        children: "·",
        className: "stats-sep"
      }),
      pdBadge,
      srcBadge
    ],
    className: "query-stats-bar"
  });
}

let StatsBar = {
  make: Page_Query$StatsBar
};

function Page_Query$TracePanel(props) {
  let onToggle = props.onToggle;
  let show = props.show;
  let label = show ? "▼ Hide trace" : "▶ Show trace";
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("button", {
        children: label,
        className: "trace-toggle",
        onClick: param => onToggle()
      }),
      show ? JsxRuntime.jsxs("table", {
          children: [
            JsxRuntime.jsx("thead", {
              children: JsxRuntime.jsxs("tr", {
                children: [
                  JsxRuntime.jsx("th", {
                    children: "Stage"
                  }),
                  JsxRuntime.jsx("th", {
                    children: "In",
                    className: "num"
                  }),
                  JsxRuntime.jsx("th", {
                    children: "Out",
                    className: "num"
                  }),
                  JsxRuntime.jsx("th", {
                    children: "Time",
                    className: "num"
                  }),
                  JsxRuntime.jsx("th", {
                    children: "Note"
                  })
                ]
              })
            }),
            JsxRuntime.jsx("tbody", {
              children: Belt_Array.mapWithIndex(props.trace, (i, t) => JsxRuntime.jsxs("tr", {
                children: [
                  JsxRuntime.jsx("td", {
                    children: t.stage,
                    className: "stage-name"
                  }),
                  JsxRuntime.jsx("td", {
                    children: String(t.rowsIn),
                    className: "num"
                  }),
                  JsxRuntime.jsx("td", {
                    children: String(t.rowsOut),
                    className: "num"
                  }),
                  JsxRuntime.jsx("td", {
                    children: fmtMs(t.elapsedMs),
                    className: "num"
                  }),
                  JsxRuntime.jsx("td", {
                    children: t.note,
                    className: "trace-note"
                  })
                ]
              }, String(i)))
            })
          ],
          className: "query-trace-table"
        }) : null
    ],
    className: "query-trace-wrapper"
  });
}

let TracePanel = {
  make: Page_Query$TracePanel
};

function Page_Query$WarningList(props) {
  let warnings = props.warnings;
  if (warnings.length === 0) {
    return null;
  } else {
    return JsxRuntime.jsx("ul", {
      children: Belt_Array.mapWithIndex(warnings, (i, w) => JsxRuntime.jsx("li", {
        children: "⚠ " + w
      }, String(i))),
      className: "query-warnings"
    });
  }
}

let WarningList = {
  make: Page_Query$WarningList
};

function Page_Query$ResultTable(props) {
  let resp = props.resp;
  let cols = getColumns(resp.rows);
  if (cols.length === 0 && resp.rows.length === 0) {
    return JsxRuntime.jsx("p", {
      children: "Query returned 0 rows.",
      className: "query-empty"
    });
  } else if (cols.length === 0) {
    return JsxRuntime.jsx("p", {
      children: "Rows returned but no displayable columns.",
      className: "query-empty"
    });
  } else {
    return JsxRuntime.jsx("div", {
      children: JsxRuntime.jsxs("table", {
        children: [
          JsxRuntime.jsx("thead", {
            children: JsxRuntime.jsx("tr", {
              children: Belt_Array.map(cols, col => JsxRuntime.jsx("th", {
                children: col
              }, col))
            })
          }),
          JsxRuntime.jsx("tbody", {
            children: Belt_Array.mapWithIndex(resp.rows, (i, row) => JsxRuntime.jsx("tr", {
              children: Belt_Array.map(cols, col => JsxRuntime.jsx("td", {
                children: getCellValue(row, col)
              }, col))
            }, String(i)))
          })
        ],
        className: "query-result-table"
      }),
      className: "query-result-scroll"
    });
  }
}

let ResultTable = {
  make: Page_Query$ResultTable
};

function Page_Query$ErrorCard(props) {
  let err = props.err;
  let match = err.line;
  let match$1 = err.col;
  let locStr = match !== undefined ? (
      match$1 !== undefined ? " at line " + String(match) + ", col " + String(match$1) : " at line " + String(match)
    ) : "";
  let other = err.errorKind;
  let kindLabel;
  switch (other) {
    case "circuit_open" :
      kindLabel = "Database unavailable";
      break;
    case "eval_error" :
      kindLabel = "Evaluation error";
      break;
    case "network_error" :
      kindLabel = "Network error";
      break;
    case "parse_error" :
      kindLabel = "Parse error";
      break;
    case "timeout" :
      kindLabel = "Query timeout";
      break;
    default:
      kindLabel = other;
  }
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: kindLabel + locStr,
        className: "query-error-kind"
      }),
      JsxRuntime.jsx("pre", {
        children: err.message,
        className: "query-error-message"
      })
    ],
    className: "query-error-card"
  });
}

let ErrorCard = {
  make: Page_Query$ErrorCard
};

function Page_Query(props) {
  let match = React.useReducer(reducer, initialState);
  let dispatch = match[1];
  let state = match[0];
  React.useEffect(() => {
    if (state.phase === "Fetching") {
      let maxRows = Belt_Option.getWithDefault(Belt_Int.fromString(state.maxRows), 500);
      Api.postQuery(state.input, state.format, maxRows).then(result => {
        if (result.TAG === "Ok") {
          dispatch({
            TAG: "GotOk",
            _0: result._0
          });
        } else {
          dispatch({
            TAG: "GotErr",
            _0: result._0
          });
        }
        return Promise.resolve();
      });
    }
  }, [state.phase]);
  let onSubmit = e => {
    e.preventDefault();
    if (state.input.trim() !== "") {
      return dispatch("Submit");
    }
  };
  let onKeyDown = e => {
    let key = e.key;
    let ctrl = e.ctrlKey || e.metaKey;
    if (ctrl && key === "Enter") {
      e.preventDefault();
      if (state.input.trim() !== "") {
        return dispatch("Submit");
      } else {
        return;
      }
    }
  };
  let isRunning = state.phase === "Fetching";
  let err = state.phase;
  let tmp;
  if (typeof err !== "object") {
    tmp = err === "Idle" ? null : JsxRuntime.jsx("div", {
        children: "Running query…",
        className: "query-loading"
      });
  } else if (err.TAG === "Done") {
    let resp = err._0;
    tmp = JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsx(Page_Query$StatsBar, {
          resp: resp
        }),
        JsxRuntime.jsx(Page_Query$TracePanel, {
          trace: resp.trace,
          show: state.showTrace,
          onToggle: () => dispatch("ToggleTrace")
        }),
        JsxRuntime.jsx(Page_Query$WarningList, {
          warnings: resp.warnings
        }),
        JsxRuntime.jsx(Page_Query$ResultTable, {
          resp: resp
        })
      ],
      className: "query-results"
    });
  } else {
    tmp = JsxRuntime.jsx(Page_Query$ErrorCard, {
      err: err._0
    });
  }
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("h1", {
            children: "Query"
          }),
          JsxRuntime.jsx("p", {
            children: "KRL pipeline syntax or SQL SELECT · Ctrl+Enter to run",
            className: "query-subtitle"
          })
        ],
        className: "query-header"
      }),
      JsxRuntime.jsx("div", {
        children: Belt_Array.map(examples, param => {
          let src = param[1];
          let label = param[0];
          return JsxRuntime.jsx("button", {
            children: label,
            className: "example-btn",
            onClick: param => dispatch({
              TAG: "LoadExample",
              _0: src
            })
          }, label);
        }),
        className: "query-examples"
      }),
      JsxRuntime.jsxs("form", {
        children: [
          JsxRuntime.jsx("div", {
            children: JsxRuntime.jsx("textarea", {
              className: "query-textarea",
              spellCheck: false,
              placeholder: "from knots | filter crossing_number == 3 | return *",
              rows: 8,
              value: state.input,
              onKeyDown: onKeyDown,
              onChange: e => dispatch({
                TAG: "SetInput",
                _0: e.target.value
              })
            }),
            className: "query-editor-area"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("label", {
                    children: "Format",
                    htmlFor: "q-format"
                  }),
                  JsxRuntime.jsxs("select", {
                    children: [
                      JsxRuntime.jsx("option", {
                        children: "Auto",
                        value: "auto"
                      }),
                      JsxRuntime.jsx("option", {
                        children: "KRL",
                        value: "krl"
                      }),
                      JsxRuntime.jsx("option", {
                        children: "SQL",
                        value: "sql"
                      })
                    ],
                    id: "q-format",
                    value: state.format,
                    onChange: e => dispatch({
                      TAG: "SetFormat",
                      _0: e.target.value
                    })
                  })
                ],
                className: "control-group"
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("label", {
                    children: "Max rows",
                    htmlFor: "q-maxrows"
                  }),
                  JsxRuntime.jsx("input", {
                    id: "q-maxrows",
                    max: "10000",
                    min: "1",
                    type: "number",
                    value: state.maxRows,
                    onChange: e => dispatch({
                      TAG: "SetMaxRows",
                      _0: e.target.value
                    })
                  })
                ],
                className: "control-group"
              }),
              JsxRuntime.jsx("button", {
                children: isRunning ? "Running…" : "▶  Run",
                className: "btn-primary query-run-btn" + (
                  isRunning ? " running" : ""
                ),
                disabled: isRunning,
                type: "submit"
              })
            ],
            className: "query-controls"
          })
        ],
        className: "query-form",
        onSubmit: onSubmit
      }),
      JsxRuntime.jsx("div", {
        children: tmp,
        className: "query-results-area"
      })
    ],
    className: "page-query"
  });
}

let make = Page_Query;

export {
  examples,
  initialState,
  reducer,
  fmtMs,
  cellText,
  getColumns,
  getCellValue,
  StatsBar,
  TracePanel,
  WarningList,
  ResultTable,
  ErrorCard,
  make,
}
/* initialState Not a pure module */
