// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Int from "@rescript/runtime/lib/es6/Belt_Int.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as View_Helpers from "./View_Helpers.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Page_KnotList(props) {
  let onNavigate = props.onNavigate;
  let onFilterChange = props.onFilterChange;
  let filters = props.filters;
  let knots = props.knots;
  let onCrossingChange = e => {
    let value = e.target.value;
    let cn = value === "" ? undefined : Belt_Int.fromString(value);
    onFilterChange({
      crossingNumber: cn,
      genus: filters.genus,
      nameSearch: filters.nameSearch
    });
  };
  let onGenusChange = e => {
    let value = e.target.value;
    let g = value === "" ? undefined : Belt_Int.fromString(value);
    onFilterChange({
      crossingNumber: filters.crossingNumber,
      genus: g,
      nameSearch: filters.nameSearch
    });
  };
  let onNameChange = e => {
    let value = e.target.value;
    onFilterChange({
      crossingNumber: filters.crossingNumber,
      genus: filters.genus,
      nameSearch: value
    });
  };
  let n = filters.crossingNumber;
  let n$1 = filters.genus;
  let tmp;
  if (typeof knots !== "object") {
    tmp = JsxRuntime.jsx(View_Helpers.Loading.make, {});
  } else if (knots.TAG === "Success") {
    let resp = knots._0;
    tmp = JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsx("p", {
          children: String(resp.count) + " knots",
          className: "result-count"
        }),
        JsxRuntime.jsxs("table", {
          children: [
            JsxRuntime.jsx("thead", {
              children: JsxRuntime.jsxs("tr", {
                children: [
                  JsxRuntime.jsx("th", {
                    children: "Name"
                  }),
                  JsxRuntime.jsx("th", {
                    children: "Crossings"
                  }),
                  JsxRuntime.jsx("th", {
                    children: "Writhe"
                  }),
                  JsxRuntime.jsx("th", {
                    children: "Genus"
                  }),
                  JsxRuntime.jsx("th", {
                    children: "Seifert Circles"
                  }),
                  JsxRuntime.jsx("th", {
                    children: "Jones Polynomial"
                  })
                ]
              })
            }),
            JsxRuntime.jsx("tbody", {
              children: Belt_Array.map(resp.knots, knot => {
                let g = knot.genus;
                let s = knot.seifertCircleCount;
                let j = knot.jonesDisplay;
                return JsxRuntime.jsxs("tr", {
                  children: [
                    JsxRuntime.jsx("td", {
                      children: knot.name,
                      className: "knot-name"
                    }),
                    JsxRuntime.jsx("td", {
                      children: String(knot.crossingNumber)
                    }),
                    JsxRuntime.jsx("td", {
                      children: String(knot.writhe)
                    }),
                    JsxRuntime.jsx("td", {
                      children: g !== undefined ? String(g) : "-"
                    }),
                    JsxRuntime.jsx("td", {
                      children: s !== undefined ? String(s) : "-"
                    }),
                    JsxRuntime.jsx("td", {
                      children: j !== undefined ? j : "-",
                      className: "jones"
                    })
                  ],
                  className: "knot-row clickable",
                  onClick: param => onNavigate({
                    TAG: "KnotDetail",
                    _0: knot.name
                  })
                }, knot.name);
              })
            })
          ],
          className: "knot-table"
        })
      ]
    });
  } else {
    tmp = JsxRuntime.jsx(View_Helpers.ErrorDisplay.make, {
      message: knots._0
    });
  }
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h1", {
        children: "Knot Database"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("label", {
                children: "Crossing Number",
                htmlFor: "filter-crossing"
              }),
              JsxRuntime.jsxs("select", {
                children: [
                  JsxRuntime.jsx("option", {
                    children: "All",
                    value: ""
                  }),
                  Belt_Array.map(Belt_Array.range(0, 10), n => {
                    let s = String(n);
                    return JsxRuntime.jsx("option", {
                      children: s,
                      value: s
                    }, s);
                  })
                ],
                id: "filter-crossing",
                value: n !== undefined ? String(n) : "",
                onChange: onCrossingChange
              })
            ],
            className: "filter-group"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("label", {
                children: "Genus",
                htmlFor: "filter-genus"
              }),
              JsxRuntime.jsxs("select", {
                children: [
                  JsxRuntime.jsx("option", {
                    children: "All",
                    value: ""
                  }),
                  Belt_Array.map(Belt_Array.range(0, 5), n => {
                    let s = String(n);
                    return JsxRuntime.jsx("option", {
                      children: s,
                      value: s
                    }, s);
                  })
                ],
                id: "filter-genus",
                value: n$1 !== undefined ? String(n$1) : "",
                onChange: onGenusChange
              })
            ],
            className: "filter-group"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("label", {
                children: "Name",
                htmlFor: "filter-name"
              }),
              JsxRuntime.jsx("input", {
                id: "filter-name",
                placeholder: "e.g. 3_1",
                type: "text",
                value: filters.nameSearch,
                onChange: onNameChange
              })
            ],
            className: "filter-group"
          })
        ],
        className: "filters"
      }),
      tmp
    ],
    className: "page-knot-list"
  });
}

let make = Page_KnotList;

export {
  make,
}
/* View_Helpers Not a pure module */
