// Generated by ReScript, PLEASE EDIT WITH CARE

import * as View_Helpers from "./View_Helpers.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Page_Dashboard(props) {
  let onNavigate = props.onNavigate;
  let stats = props.stats;
  let tmp;
  if (typeof stats !== "object") {
    tmp = JsxRuntime.jsx(View_Helpers.Loading.make, {});
  } else if (stats.TAG === "Success") {
    let s = stats._0;
    let n = s.minCrossings;
    let n$1 = s.maxCrossings;
    tmp = JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("div", {
              children: String(s.totalKnots),
              className: "stat-value"
            }),
            JsxRuntime.jsx("div", {
              children: "Total Knots",
              className: "stat-label"
            })
          ],
          className: "stat-card"
        }),
        JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("div", {
              children: n !== undefined ? String(n) : "-",
              className: "stat-value"
            }),
            JsxRuntime.jsx("div", {
              children: "Min Crossings",
              className: "stat-label"
            })
          ],
          className: "stat-card"
        }),
        JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("div", {
              children: n$1 !== undefined ? String(n$1) : "-",
              className: "stat-value"
            }),
            JsxRuntime.jsx("div", {
              children: "Max Crossings",
              className: "stat-label"
            })
          ],
          className: "stat-card"
        }),
        JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("div", {
              children: String(s.schemaVersion),
              className: "stat-value"
            }),
            JsxRuntime.jsx("div", {
              children: "Schema Version",
              className: "stat-label"
            })
          ],
          className: "stat-card"
        }),
        JsxRuntime.jsx(View_Helpers.DistributionTable.make, {
          title: "Crossing Number Distribution",
          data: s.crossingDistribution
        }),
        JsxRuntime.jsx(View_Helpers.DistributionTable.make, {
          title: "Genus Distribution",
          data: s.genusDistribution
        }),
        JsxRuntime.jsx("div", {
          children: JsxRuntime.jsx("button", {
            children: "Browse Knots",
            className: "btn-primary",
            onClick: param => onNavigate("KnotList")
          }),
          className: "actions"
        })
      ],
      className: "stats-grid"
    });
  } else {
    tmp = JsxRuntime.jsx(View_Helpers.ErrorDisplay.make, {
      message: stats._0
    });
  }
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h1", {
        children: "QuandleDB"
      }),
      JsxRuntime.jsx("p", {
        children: "A knot-theory database powered by Skein.jl",
        className: "subtitle"
      }),
      tmp
    ],
    className: "page-dashboard"
  });
}

let make = Page_Dashboard;

export {
  make,
}
/* View_Helpers Not a pure module */
