// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js from "@rescript/runtime/lib/es6/Js.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";

function fromPath(path) {
  let segments = Belt_Array.keep(path.split("/"), s => s !== "");
  let len = segments.length;
  if (len >= 3) {
    return "NotFound";
  }
  switch (len) {
    case 0 :
      return "Dashboard";
    case 1 :
      let match = segments[0];
      switch (match) {
        case "knots" :
          return "KnotList";
        case "query" :
          return "Query";
        default:
          return "NotFound";
      }
    case 2 :
      let match$1 = segments[0];
      if (match$1 !== "knots") {
        return "NotFound";
      }
      let name = segments[1];
      return {
        TAG: "KnotDetail",
        _0: name
      };
  }
}

function toPath(route) {
  if (typeof route === "object") {
    return "/knots/" + route._0;
  }
  switch (route) {
    case "Dashboard" :
      return "/";
    case "KnotList" :
      return "/knots";
    case "Query" :
      return "/query";
    case "NotFound" :
      return "/404";
  }
}

function fromUrl() {
  let match = Js.undefinedToOption(typeof window === "undefined" ? undefined : window);
  return fromPath(match !== undefined ? window.location.pathname : "/");
}

export {
  fromPath,
  toPath,
  fromUrl,
}
/* No side effect */
