// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Route from "./Route.res.mjs";
import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_SortArray from "@rescript/runtime/lib/es6/Belt_SortArray.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Primitive_string from "@rescript/runtime/lib/es6/Primitive_string.js";
import * as JsxRuntime from "react/jsx-runtime";

function View_Helpers$NavBar(props) {
  let onNavigate = props.onNavigate;
  let currentRoute = props.currentRoute;
  let navLink = (route, label) => {
    let isActive = Primitive_object.equal(currentRoute, route);
    return JsxRuntime.jsx("a", {
      children: label,
      className: isActive ? "nav-link active" : "nav-link",
      href: Route.toPath(route),
      onClick: e => {
        e.preventDefault();
        onNavigate(route);
      }
    });
  };
  return JsxRuntime.jsxs("nav", {
    children: [
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsx("a", {
          children: "QuandleDB",
          className: "brand-link",
          href: "/",
          onClick: e => {
            e.preventDefault();
            onNavigate("Dashboard");
          }
        }),
        className: "navbar-brand"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          navLink("Dashboard", "Dashboard"),
          navLink("KnotList", "Knots"),
          navLink("Query", "Query")
        ],
        className: "navbar-links"
      })
    ],
    className: "navbar"
  });
}

let NavBar = {
  make: View_Helpers$NavBar
};

function View_Helpers$Loading(props) {
  return JsxRuntime.jsx("div", {
    children: "Loading...",
    className: "loading"
  });
}

let Loading = {
  make: View_Helpers$Loading
};

function View_Helpers$ErrorDisplay(props) {
  return JsxRuntime.jsx("div", {
    children: props.message,
    className: "error-message"
  });
}

let ErrorDisplay = {
  make: View_Helpers$ErrorDisplay
};

function View_Helpers$DistributionTable(props) {
  let entries = Belt_SortArray.stableSortBy(Js_dict.entries(props.data), (param, param$1) => Primitive_string.compare(param[0], param$1[0]));
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h3", {
        children: props.title
      }),
      JsxRuntime.jsxs("table", {
        children: [
          JsxRuntime.jsx("thead", {
            children: JsxRuntime.jsxs("tr", {
              children: [
                JsxRuntime.jsx("th", {
                  children: "Value"
                }),
                JsxRuntime.jsx("th", {
                  children: "Count"
                })
              ]
            })
          }),
          JsxRuntime.jsx("tbody", {
            children: Belt_Array.map(entries, param => {
              let key = param[0];
              return JsxRuntime.jsxs("tr", {
                children: [
                  JsxRuntime.jsx("td", {
                    children: key
                  }),
                  JsxRuntime.jsx("td", {
                    children: String(param[1])
                  })
                ]
              }, key);
            })
          })
        ]
      })
    ],
    className: "distribution-table"
  });
}

let DistributionTable = {
  make: View_Helpers$DistributionTable
};

export {
  NavBar,
  Loading,
  ErrorDisplay,
  DistributionTable,
}
/* react/jsx-runtime Not a pure module */
